### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [CASES-LU/TACOS#15]
https://f-droid.org/wiki/index.php?title=lu.cases.tacos/lastbuild_23&oldid=280318

**Comment by IzzySoft** [comment]
Could you help fixing that build, @cedricbonhomme (or one of the other contributors here)? Until then, your app is not listed at F-Droid (as that's the only build it has) – which means it would be "pruned" (no active version available for several months and no fix in sight => unlist). Thanks in advance!
